spring:
  application:
    name: CustomerService

  # Keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/ticketing-security-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8086

# Keycloak variable
keycloak:
  auth-server-url: http://localhost:8091/auth
  realm: ticketing-security-realm
  resource: admin-cli
  credentials:
    secret: 7OG9c3igAtRjCRnRbyjCdSRXgljsqgYY
  scheduled:
    mapping:
      initialDelay: 10000 # 10s
      fixedRate: 86 400 000 # 24h
  auth:
    converter:
      ressource-id: ticketing-security-realm
      principal-attribute: preferred_username


#OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

#logging:
#  level:
#    root: debug