spring:
  application:
    name: CustomerService

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

keycloak:
  auth-server-url: http://localhost:8091/auth
  realm: ticketing-security-realm
  resource: admin-cli
  credentials:
    secret: 7OG9c3igAtRjCRnRbyjCdSRXgljsqgYY
  scheduled:
    mapping:
      initialDelay: 10000 # 10s
      fixedRate: 86 400 000 # 24h


server:
  port: 8086

#OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

#logging:
#  level:
#    root: debug